/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module top (
  input PE,
  input Red,
  input Bateria,
  input Sol,
  output Energizador,
  output Conmutador
);
  assign Conmutador = ((Red & Sol) | ((Red | Sol) & ~ Bateria));
  assign Energizador = PE;
endmodule
